### ISSUE TITLE
请问ntu120与ntu60的预处理代码为什么是一样的，sgn那个只有ntu60的预处理

### ISSUE THREAD

**Issue by YujieOuO** [fabro66/Online-Skeleton-based-Action-Recognition#1]

**Comment by fabro66** [comment]
您好！NTU120和NTU60数据的预处理文件get_raw_denoised_data.py和get_raw_skes_data.py是相同的，但是划分验证标准的代码文件seq_transformation.py是不一样的。

seq_transformation.py(NTU60):
https://github.com/fabro66/Online-Skeleton-based-Action-Recognition/blob/6f69fe54c4d19a99d25cbc294e62632e72fc25ad/data/ntu60/seq_transformation.py#L189

seq_transformation.py(NTU120):
https://github.com/fabro66/Online-Skeleton-based-Action-Recognition/blob/6f69fe54c4d19a99d25cbc294e62632e72fc25ad/data/ntu120/seq_transformation.py#L189

**Comment by YujieOuO** [comment]
十分感谢，数据处理好后应该可以直接套用sgn对ntu60的代码吧，如果只用cs数据集的话，我看ntu120和60的代码是一样的

**Comment by fabro66** [comment]
数据预处理后，可以直接用SGN跑了，不过--dataset 这个参数要设置为NTU120，即：
```
# For the CSub setting
python  main.py --network SGN --dataset NTU120 --train 0 --case 0 
# For the CSet setting
python  main.py --network SGN --dataset NTU120 --train 0 --case 1
```
Cross Subject验证标准都是基于不同行为主体划分的，代码基本一样，只是Subject的数量增加了.

**Comment by YujieOuO** [comment]
感谢大佬，帮大忙了😘

**Comment by YujieOuO** [comment]
大佬你好，我想请教一下您的NTU-GAST60数据集可以用于sgn分类吗，或者如果我想用sysu数据集的话sgn项目里的h5文件该如何生成呢，谢谢了

**Comment by fabro66** [comment]
你好，我不是大佬，NTU-GAST60数据集跟NTU原始的骨架数据一样都是可以用于sgn分类的。
对于SYSU数据集，我没有用过，所以也不清楚如何生成h5文件。

**Comment by YujieOuO** [comment]
十分感谢您的回复，其实我现在的一项工作是基于sgn做的一个零样本动作识别，模型都弄完了但是老师说数据集只有ntu60和ntu120的话不够，看到您有一个新的数据集就想试试能不能导入sgn。所以不知道您有用sgn对gast60数据集进行分类过吗，如果有开源代码的话就非常感谢了，本人也是刚从事这一块，工程能力确实很勉强，所以也是想在快截稿的时候看看能不能加个新数据集。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junfa Liu"<notifications@github.com&gt;; 
发送时间: 2021年2月23日(星期二) 下午4:41
收件人: "fabro66/Online-Skeleton-based-Action-Recognition"<Online-Skeleton-based-Action-Recognition@noreply.github.com&gt;; 
抄送: "周彧杰"<453252496@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fabro66/Online-Skeleton-based-Action-Recognition] 请问ntu120与ntu60的预处理代码为什么是一样的，sgn那个只有ntu60的预处理 (#1)





 
你好，我不是大佬，NTU-GAST60数据集跟NTU原始的骨架数据一样都是可以用于sgn分类的。
 对于SYSU数据集，我没有用过，所以也不清楚如何生成h5文件。

**Comment by YujieOuO** [comment]
你好，我想再询问一下这个gast60数据集有没有相应的官方介绍呢，类似于标签内容，数据结构之类的，谢谢了

**Comment by fabro66** [comment]
gast60与ntu60的标签是一样的，只是关节点数量不一样，有关这个数据集介绍的文章录用了，不过还没公开发表。
建议你加入另一个常用的骨架数据 [kinetics-skeleton 400](https://github.com/yysijie/st-gcn/blob/master/OLD_README.md)

**Comment by YujieOuO** [comment]
emm，我现在的一项工作是基于sgn做的一个零样本动作识别，模型弄完了但是数据集不够，老师说得加一个新的数据集，小一点的都行。这样的话是不是说gast60数据集本质上和ntu60是一个数据集，不能作为一个新的数据集加入了呢。

**Comment by YujieOuO** [comment]
如果能加这个数据集的话，也可以算一个贡献，可以一起合作呀
