### ISSUE TITLE
GAST-Skeleton Dataset Download

### ISSUE THREAD

**Issue by ArkarPhyo1310** [fabro66/Online-Skeleton-based-Action-Recognition#3]
First of all, Thanks you for great work.
Can you please upload the GAST-skeleton to google drive?

**Comment by fabro66** [comment]
Hi~ 
We will upload the NTU-GAST skeleton to google drive next week. After uploading, I will remind you again.

**Comment by ArkarPhyo1310** [comment]
Thank you very much!

**Comment by fabro66** [comment]
Hi~
I have uploaded NTU-GAST Skeleton in Google drive. Please check it in README.md.
